[Hotkey/TriggerKeys]
0=Control+space

[Behavior]
ActiveByDefault=True
resetStateWhenFocusIn=No
ShareInputState=All
PreeditEnabledByDefault=True
AllowInputMethodForPassword=False
ShowPreeditForPassword=False
